### ISSUE TITLE
Write an Exact Euler/Riemann Solver

### ISSUE THREAD

**Issue by bcaddy** [bcaddy/hydro-sandbox#4]
# Overview

- [x] Write documentation using doxygen

- [x] Create a struct for the grid. 

- [x] Create classes for the simulation

- [x] Write the main function

- [x] Write a visualizer

- [x] My original implementation had issues. Namely that the fluxes were recomputed for each cell and that can lead to numerical instabilities so now I'm fixing and enhancing the code.

# Details
Stretch goals in *italics*

## Using Doxygen
- [x] Make myself a cheatsheet for Doxygen
- [x] Explore my doxygen VSC plugins

#### Member variables 
- [x] velocity
- [x] density
- [x] pressure
- [x] numGhostCells
- [x] numRealCells
- [x] totNumCells
- [x] Files (type std::ofstream from std::fstream)

#### Member functions 
Those that will require template functionality are indicated. Functions that might not need to be part of the class are indicated with "?".
- [x] Calculate momentum
- [x] Access the ith element of each array
- [x] Save output, use CSV for now, making three separate CSV files is probably easiest. *future versions will use HDF5*
- [x] Set and updated boundary conditions (template: periodic, *outflow, reflect, inflow, hydrostatic*)

#### Member Variables (private unless otherwise indicated)
- [x] cR and cL for sound speed on left and right side
- [x] pressureStar
- [x] velocityStar
- [x] densityStar
- [x] Left and right state variables
- [x] gamma
- [x] position
- [x] time

#### Member Functions (private unless otherwise indicated)
- [x] Determine pStar
    - [x] guess pStar
- [x] f_k and f'_k
- [x] computeVStar
- [x] speed of shocks
- [x] speed of rarefaction, both head and tail
- [x] Compute fluxes
- [x] compute shock density
- [x] compute density for the star state next to a rarefaction
- [x] compute all values within a rarefaction
- [x] riemannMain (public)

#### Member Variables
- [x] Current grid
- [x] Next time step grid
- [x] physLen
- [x] deltaX
- [x] timeStep
- [x] CFLNum
- [x] limiterKind
- [x] initialConditionKind
- [x] current time

#### Member Functions
- [x] Set initial conditions (template: Sod, *Sedov, advection, slow moving shock*)
- [x] Limiters (template: MC, *minmod*)
- [x] Compute time step
    - Zingale eqn. 8.57, Toro Section 6.3.2
- [x] Reconstruct interface states (template for using piecewise linear or parabolic. Start with the first only)
- [x] Call Riemann Solver
- [x] Perform the conservative update
- [x] Update the primitive values at the end of the loop
- [x] update current time

## The Main Function
This function should:
- [x] contain all the settings (what limiter to use, initial conditions, etc)
- [x] call member functions
- [x] provide console output to the user
- [x] note the current time and choose when to stop the simulation

## Visualizer Code
Look at Evan's sod shock plotter code and make something like that paired with my animation code. The final product should provide an animation with velocity, density, pressure, and internal energy. Maybe stack them so it's clearer where each feature lines up with other features.
- [x] Did that
- [x] Modify it to compute internal energy instead of specific internal energy. Compare with Cholla fiducial Sod plot

### Research Items
- [x] Templates
- [x] Namespaces

### Todos
- [x] Refactor to save arrays of interface states and fluxes and then update all the grid elements at once
  - [x] Remove all the stuff for grids that don't get saved
  - [x] Interface states
    - [x] Quick and dirty implementation of piecewise constant reconstruction
    - [x] Add separate functions for PLM and PCM interface reconstruction which are called by Simulation1D::interfaceStates
    - [x] Re-implement MC limiter
- [x] Move commonly used functions and methods to a header only namespace. This is C++'s version of a "utility class"
  - [x] sound speed
    - [x] Include Nan detection
  - [x] momentum
  - [x] pressure
  - [x] energy
  - [x] velocity
- [x] Fix up animation program to more elegantly deal with short animations and to always compute an integer stride
- [x] Clean up documentation. As I go but also do a full pass when I'm done
  - [x] document new initial conditions and limiters
- [x] Run tests
  - [x] Implement new boundary and initial conditions.
