### ISSUE TITLE
Create a 1D Euler Solver using a Van Leer integrator

### ISSUE THREAD

**Issue by bcaddy** [bcaddy/hydro-sandbox#8]
# Tasks

- [x] Move the old euler solver to `eulerSolver1D-CTU`

- [x] Copy the contents of that directory to a new directory titled `eulerSolver1D-VL`

- [x] Update shell scripts and doxygen documentation to account for the changes
  - different doxygen things for each directory??

- [x] Modify contents of `eulerSolver1D-VL` to use Van Leer algorithm

## Van Leer Algorithm

1. Compute first order interface states

2. Solve Riemann problem

3. Perform a conservative update to compute the **temporary** half time step values for the conserved variables

4. Compute the interface states with a high order method (PLM) using the half time step conserved variables

5. Solve the Riemann problem for the half time step interface states

6. Perform a conservative update on the permanent grid using the fluxes from the second Riemann solve

### Interface computations
- [x] A way to choose on the fly between first and second order interface states. Might need to ditch a current member variable or use it to choose highest order 

- [x] A way to choose if I'm using the primary grid or the half time step grid

### Conservative update
- [x] Choose between updating the real grid or the half time step grid

### Member variables
- [x] a temporary grid for storing half time step values

### Grid
- [x] Create a simple grid struct for storing the grid of primitive variables

# Resolving Issues/Bugs
- [x] The ghost cells in the half time step grid need to be updated as well
- [x] Van Leer doesn't require characteristic tracing so that needs to be removed

**Comment by bcaddy** [comment]
As of today it's mostly done. I'm getting complex sound speeds though so something is off. Likely in the conservative update

**Comment by bcaddy** [comment]
I figured out the issue. I wasn't updating the half time step grid with the boundary conditions. 

Now however I'm getting very diffusive behavior with a spread out shock
